name: run_build_after_push
on:
  push:
    branches:
      - Rahman-Dev-0.0.1
jobs:  
  build:      
    name: Build & Release 
    runs-on: ubuntu-latest 

    steps:
        #1 Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v6

        #2 Setup Java
      - name: Set Up Java
        uses: actions/setup-java@v5.1.0
        with:
          distribution: 'oracle'
          java-version: '17'

        #3 Setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2.21.0
        with:
          flutter-version: '3.35.7'
          channel: 'stable'

        #4 Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

        #5 Setup Keystore
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks
          
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties
        
       #6 Building APK
      - name: Build APK
        run: flutter build apk --release  --build-number=${{ github.run_number }}

        #7 Building App Bundle (aab)
      - name: Build appBundle
        run: flutter build appbundle  --build-number=${{ github.run_number }}

        #8 Building Web
      - name: Build Web
        run: flutter build web

        #9 Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
            build/web

       
      #10 Extract version (name only) + CI build number
      - name: Extract version from pubspec.yaml
        run: |
             BASE_VERSION=$(grep '^version:' pubspec.yaml | cut -d ':' -f2 | cut -d '+' -f1 | xargs)
             FINAL_VERSION="${BASE_VERSION}+${{ github.run_number }}"
             echo "VERSION=$FINAL_VERSION" >> $GITHUB_ENV


        
        
        #11 Create Release
      - name: Create Release
        uses: ncipollo/release-action@v1.20.0
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/app/outputs/bundle/release/app-release.aab"
          tag: v${{ env.VERSION }}
          token: ${{ secrets.TOKEN }}