name: run_build_after_push
on:
  push:
    branches:
      - main

jobs:  
  build:      
    name: Build & Release 
    runs-on: ubuntu-latest 

    steps:
      # 1️⃣ Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v6

      # 2️⃣ Setup Java (required for Android build)
      - name: Set Up Java
        uses: actions/setup-java@v5.1.0
        with:
          distribution: 'oracle'
          java-version: '17'

      # 3️⃣ Setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2.21.0
        with:
          flutter-version: '3.35.7'
          channel: 'stable'

      # 4️⃣ Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

      # 5️⃣ Setup Keystore
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties

      # 6️⃣ Build APK
      - name: Build APK
        run: flutter build apk --release --build-number=${{ github.run_number }}

      # 7️⃣ Build App Bundle (AAB)
      - name: Build App Bundle
        run: flutter build appbundle --build-number=${{ github.run_number }}

      # 8️⃣ Extract version from pubspec.yaml
      - name: Extract version from pubspec.yaml
        run: |
          BASE_VERSION=$(grep '^version:' pubspec.yaml | cut -d ':' -f2 | cut -d '+' -f1 | xargs)
          FINAL_VERSION="${BASE_VERSION}+${{ github.run_number }}"
          echo "VERSION=$FINAL_VERSION" >> $GITHUB_ENV

      # 9️⃣ Push APK to another repo
      - name: Push APK to storage repo
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git clone https://x-access-token:${TOKEN}@github.com/smdabdulrahman/selldroid-releases.git
          cd apk-releases

          mkdir -p android
          cp ../build/app/outputs/flutter-apk/app-release.apk android/app-${{ env.VERSION }}.apk

          git add .
          git commit -m "Add APK v${{ env.VERSION }}" || echo "No changes to commit"
          git push
